# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.0.0

jobs:
  build-app:
    description: Build and run tests
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get .
      - run:
          name: Build release
          command: go build .
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - '/home/circleci/go/pkg/mod'
      - persist_to_workspace:
          root: .
          paths:
            - gogin-example
            - Dockerfile

workflows:
  build_and_push:
    jobs:
      - build-app:
          name: build-app
      - aws-ecr/build-and-push-image:
          requires:
            - build-app
          name: build-and-push-image
          repo: sample-repo
          tag: 'latest,v0.1.<<pipeline.number>>'
          dockerfile: Dockerfile
          attach-workspace: true
          checkout: false
          path: .
          filters:
            branches:
              only: main
          context:
            - eu-central-1-ecr
